// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removed_constraints_in_customer_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_constraints_in_customer_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202205200354438_removed_constraints_in_customer_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
