// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _rate_added_to_rental : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_rate_added_to_rental));
        
        string IMigrationMetadata.Id
        {
            get { return "202206060341359__rate_added_to_rental"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
