// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_moviestbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_moviestbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202205160416195_add_moviestbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
