// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alter_id_to_genreid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_id_to_genreid));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180854000_alter_id_to_genreid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
