// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class data_conversion_movies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data_conversion_movies));
        
        string IMigrationMetadata.Id
        {
            get { return "202206060604401_data_conversion_movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
