// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_genretbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_genretbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180751375_add_genretbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
