// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class foreign_key_added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreign_key_added1));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180947224_foreign_key_added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
